language: python
dist: xenial
python:
- '3.6'
- '3.7'
- '3.8-dev'
install:
- pip install -r requirements.txt
- pip install -e .
before_script:
- pip install -r test_requirements.txt
script:
- py.test --verbose --color=yes --flake8 --pylint --cov-report=xml --cov=tr064 tr064 tests
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: gDmlF/lH/Nx4I6zfLeHbuLmEr6J4j+gDAeNAQa75M8dKq8IcaOyUYeVqYtAxrRje8KiVhLc/w9ic+AJnWlMb/MgfPzuVP7Bu3Igni88vGVV2AmsoLi4YoEd8F7fkb7QXFYjpO33Uh0bLQp6tizPsNGsSl7/hjRCig+fd8Fx2rSV1dnhCCMqqJJpsT6GT9jon1ZUc/v0YHO1LWRIcogTrFJVVWstbrO0w6PJzixRCQQejnW65KoJbOUUUV2faiXSvPOI7UvDrd/pRHekOltkpT9jIIcZZeKSeHa7jpm35uAFVtPdC6G4/QXCR8esCAcEie16T5K4TwfcmsDlJ0LLekZl+kEt1XMjcs9psvCjShwHs6qOfbz4YCkuul6XJR2/s4E86dL3//DuEogk78TIP/ZoE6Uw3t8ghe6QLXMGhgPaZLjQg0KPzfYMzPnxk78qgbc1fL3B5xcsuRpMDZgmRY/1dDcOQuGIOWmfZCjpQN4JqFokntMhtjX7IIo3zpGfB3VeDFjx+Ftv7oEudSb2SgKec+rmh6nrWkD8WeVviWlZYbO7TqfYm6JgEkawJemwGcRRk5/4iJlL98g1y0IiAqpxKzF0IBDXbtsHERb9XtWAXsj2WmIIGLDFcuODiCaV7Ms0Xf3LtUOwxuvPLWbZmh4WjgZrvqZZIcv4/kg4DbS4=
  on:
    tags: true
  skip_existing: true
